const userTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_SIGN_IN_SUCCESS: 'SET_SIGN_IN_SUCCESS',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_OUT_USER_START: 'SIGN_OUT_USER_START',
  SIGN_OUT_USER_SUCCESS: 'SIGN_OUT_USER_SUCCESS',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_ERROR: 'RESET_PASSWORD_ERROR',
};

export default userTypes;
